export const educacaoTheme = {
  background: "var(--color-panel-bg)",
  backgroundSoft: "var(--color-panel-bg-soft)",
  surface: "var(--color-panel-card)",
  surfaceStrong: "var(--color-panel-card-strong)",
  border: "var(--color-panel-border)",
  text: "var(--color-text-main)",
  textMuted: "var(--color-text-muted)",
  textSoft: "var(--color-text-soft)",
  accentBlue: "#007FFE",
  accentGreen: "#77C56B",
  accentGold: "#FCD418",
  accentOrange: "#F2994A",
  accentCyan: "#73D2DE",
  accentRed: "#F77777",
  chartPalette: ["#007FFE", "#71B434", "#FCD418", "#F2994A", "#73D2DE"],
};
